name: Release
on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: pnpm

      - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

      - run: pnpm install
      - run: pnpm build

      # Only create snapshot for now, re-enable once the dex is released
      # - name: Create PR or Publish release
      #   uses: changesets/action@v1
      #   id: changesets
      #   with:
      #     commit: "chore: update versions"
      #     title: "chore: update versions"
      #     publish: pnpm changeset publish
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish snapshot
        run: |
          pnpm -r exec npm version 0.0.0-snapshot.$(git rev-parse --short HEAD) --git-tag-version=false
          pnpm -r publish --no-git-checks --tag snapshot
