name: Release
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: pnpm

      - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

      - run: pnpm install

      # Only create snapshot for now, re-enable once the dex is released
      - name: Create PR or Publish release
        uses: changesets/action@v1
        id: changesets
        with:
          publish: echo "damn you changesets"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
